# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\arka\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\graph_plot\graph_plot_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphPlotDialogBase(object):
    def setupUi(self, GraphPlotDialogBase):
        GraphPlotDialogBase.setObjectName("GraphPlotDialogBase")
        GraphPlotDialogBase.resize(701, 771)
        self.adj_file_path = QtWidgets.QLineEdit(GraphPlotDialogBase)
        self.adj_file_path.setGeometry(QtCore.QRect(280, 10, 371, 31))
        self.adj_file_path.setObjectName("adj_file_path")
        self.adj_csv_loader = QtWidgets.QPushButton(GraphPlotDialogBase)
        self.adj_csv_loader.setGeometry(QtCore.QRect(660, 10, 31, 31))
        self.adj_csv_loader.setObjectName("adj_csv_loader")
        self.label = QtWidgets.QLabel(GraphPlotDialogBase)
        self.label.setGeometry(QtCore.QRect(10, 10, 261, 31))
        self.label.setObjectName("label")
        self.adjacency_table = QtWidgets.QTableWidget(GraphPlotDialogBase)
        self.adjacency_table.setGeometry(QtCore.QRect(10, 320, 681, 301))
        self.adjacency_table.setObjectName("adjacency_table")
        self.adjacency_table.setColumnCount(0)
        self.adjacency_table.setRowCount(0)
        self.log_box = QtWidgets.QTextBrowser(GraphPlotDialogBase)
        self.log_box.setGeometry(QtCore.QRect(10, 110, 681, 181))
        self.log_box.setObjectName("log_box")
        self.load_data_btn = QtWidgets.QPushButton(GraphPlotDialogBase)
        self.load_data_btn.setGeometry(QtCore.QRect(10, 730, 151, 31))
        self.load_data_btn.setObjectName("load_data_btn")
        self.plot_btn = QtWidgets.QPushButton(GraphPlotDialogBase)
        self.plot_btn.setGeometry(QtCore.QRect(170, 730, 161, 31))
        self.plot_btn.setObjectName("plot_btn")
        self.label_2 = QtWidgets.QLabel(GraphPlotDialogBase)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 261, 31))
        self.label_2.setObjectName("label_2")
        self.coords_file_path = QtWidgets.QLineEdit(GraphPlotDialogBase)
        self.coords_file_path.setGeometry(QtCore.QRect(280, 60, 371, 31))
        self.coords_file_path.setObjectName("coords_file_path")
        self.coords_csv_loader = QtWidgets.QPushButton(GraphPlotDialogBase)
        self.coords_csv_loader.setGeometry(QtCore.QRect(660, 60, 31, 31))
        self.coords_csv_loader.setObjectName("coords_csv_loader")
        self.close_layers_btn = QtWidgets.QPushButton(GraphPlotDialogBase)
        self.close_layers_btn.setGeometry(QtCore.QRect(340, 730, 171, 31))
        self.close_layers_btn.setObjectName("close_layers_btn")
        self.commit_btn = QtWidgets.QPushButton(GraphPlotDialogBase)
        self.commit_btn.setGeometry(QtCore.QRect(520, 730, 171, 31))
        self.commit_btn.setObjectName("commit_btn")
        self.edge_thres_slider = QtWidgets.QSlider(GraphPlotDialogBase)
        self.edge_thres_slider.setGeometry(QtCore.QRect(290, 680, 301, 31))
        self.edge_thres_slider.setOrientation(QtCore.Qt.Horizontal)
        self.edge_thres_slider.setObjectName("edge_thres_slider")
        self.label_3 = QtWidgets.QLabel(GraphPlotDialogBase)
        self.label_3.setGeometry(QtCore.QRect(20, 680, 261, 31))
        self.label_3.setObjectName("label_3")
        self.threshold_label = QtWidgets.QLabel(GraphPlotDialogBase)
        self.threshold_label.setGeometry(QtCore.QRect(620, 680, 61, 31))
        self.threshold_label.setObjectName("threshold_label")
        self.del_edge_btn = QtWidgets.QPushButton(GraphPlotDialogBase)
        self.del_edge_btn.setGeometry(QtCore.QRect(470, 630, 221, 31))
        self.del_edge_btn.setObjectName("del_edge_btn")

        self.retranslateUi(GraphPlotDialogBase)
        QtCore.QMetaObject.connectSlotsByName(GraphPlotDialogBase)

    def retranslateUi(self, GraphPlotDialogBase):
        _translate = QtCore.QCoreApplication.translate
        GraphPlotDialogBase.setWindowTitle(_translate("GraphPlotDialogBase", "GraphPlot"))
        self.adj_csv_loader.setText(_translate("GraphPlotDialogBase", "..."))
        self.label.setText(_translate("GraphPlotDialogBase", "Load adjacency matrix"))
        self.load_data_btn.setText(_translate("GraphPlotDialogBase", "LOAD DATA"))
        self.plot_btn.setText(_translate("GraphPlotDialogBase", "PLOT"))
        self.label_2.setText(_translate("GraphPlotDialogBase", "Load Vertex coordinates"))
        self.coords_csv_loader.setText(_translate("GraphPlotDialogBase", "..."))
        self.close_layers_btn.setText(_translate("GraphPlotDialogBase", "CLOSE LAYERS"))
        self.commit_btn.setText(_translate("GraphPlotDialogBase", "COMMIT"))
        self.label_3.setText(_translate("GraphPlotDialogBase", "Choose Edge weight threshold"))
        self.threshold_label.setText(_translate("GraphPlotDialogBase", "0"))
        self.del_edge_btn.setText(_translate("GraphPlotDialogBase", "DELETE EDGE"))
